### ISSUE TITLE
todui add fails on mac os

### ISSUE THREAD

**Issue by gitmalong** [danimelchor/todui#2]
% todui add steuer
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/todui-0.1.0/src/cli/cli_utils.rs:9:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by danimelchor** [comment]
Thanks for catching this! It is now fixed here: https://github.com/danimelchor/todui/pull/3
